require: rubocop-rails

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'
    # - '**/*.rb'
    # - '**/app/models/concerns/*.rb'

Metrics/AbcSize:
  Max: 20

Rails:
  Enabled: true

Style/AsciiComments:
#   Description: 'Use only ascii symbols in comments.'
#   StyleGuide: '#english-comments'
  Enabled: false
